default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  primary: &primary_production
    <<: *default
    database: pharma_temp_production
    username: pharma_temp
    password: <%= ENV["PHARMA_TEMP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: pharma_temp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pharma_temp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pharma_temp_production_cable
    migrations_paths: db/cable_migrate
