require 'digest'

class BatchesController < ApplicationController
  def index
    @batches = generate_demo_batches(12)
    render layout: false
  end
  
  def show
    @batch = generate_batch_data(params[:id])
    
    if request.format.pdf?
      pdf = generate_compliance_pdf(params[:id], @batch)
      send_data pdf.render,
                filename: "chain-of-custody-#{params[:id]}.pdf",
                type: 'application/pdf',
                disposition: 'inline'
    else
      render layout: false
    end
  end

  private

  def generate_demo_batches(count)
    (1..count).map do |i|
      {
        id: "LOT-#{i}-#{Time.now.strftime('%Y%m%d%H%M')}",
        status: %w[IN_TRANSIT DELIVERED PENDING].sample,
        temp: "#{rand(1.8..8.2).round(1)}°C",
        location: ['PHX Warehouse', 'Tucson Distro', 'I-10 East', 'Sky Harbor', 'Banner Health'].sample,
        eta: (rand(2..24).hours).from_now.strftime('%m/%d %H:%M')
      }
    end
  end

  def generate_batch_data(batch_id)
    {
      id: batch_id,
      product: batch_id.include?('INSULIN') ? 'Insulin (2-8°C)' : 
               batch_id.include?('BIOLOGICS') ? 'Biologics (-20°C)' : 'Pharma Cold Chain',
      status: %w[IN_TRANSIT DELIVERED PENDING].sample,
      temperature: "#{rand(1.8..8.2).round(1)}°C",
      location: ['Phoenix AZ', 'Tucson AZ', 'Flagstaff AZ', 'I-10 East', 'Sky Harbor'].sample,
      handler: ['B. Thomas - Thomas IT', 'Driver AZ123', 'Receiving PHX-01', 'QC Inspector'].sample,
      events: 8.times.map do |i|
        time_ago = (rand(24.hours).ago + (i * 1.hour))
        {
          timestamp: time_ago.utc.iso8601,
          action: %w[PICKED_UP SCAN TEMP_CHECK GEOFENCE TRANSIT DELIVERED SIGNED][i % 7],
          temp: "#{rand(1.8..8.2).round(1)}°C",
          location: ['PHX Cold Storage', 'I-10 E 45mi', 'Tucson Distro', 'Banner Health PHX', 'Final Delivery'][i % 5]
        }
      end.sort_by { |e| e[:timestamp] }
    }
  end

  def generate_compliance_pdf(batch_id, data)
    pdf = Prawn::Document.new(page_size: 'LETTER', margin: 50)
    pdf.font 'Helvetica'

    # 21 CFR Part 11 Header
    pdf.fill_color '#1e3c72'
    pdf.text_box '21 CFR PART 11 COMPLIANT', {
      at: [40, 750], size: 16, style: :bold
    }
    pdf.text_box 'CHAIN OF CUSTODY DOCUMENT', {
      at: [40, 725], size: 24, style: :bold
    }

    # Batch Summary Table
    pdf.fill_color '000000'
    pdf.move_down 80
    pdf.table([
      ['Batch ID', data[:id]],
      ['Product Type', data[:product]],
      ['Current Status', data[:status]],
      ['Temperature', data[:temperature]],
      ['Current Location', data[:location]],
      ['Last Handler', data[:handler]],
      ['Document Generated', Time.now.utc.iso8601[0..19]],
      ['Document Hash', Digest::SHA256.hexdigest("#{batch_id}#{Time.now.utc.iso8601}")]
    ], width: 500, cell_style: { inline_format: true }) do
      row(0).font_style = :bold
      row(0).background_color = '#1e3c72'
      row(0).text_color = 'FFFFFF'
      cells.border_width = 1
      cells.border_color = 'CCCCCC'
    end

    # Audit Trail Header
    pdf.move_down 40
    pdf.fill_color '#1e3c72'
    pdf.text 'SECURE AUDIT TRAIL (Immutable 21 CFR §11.10)', 
             size: 14, style: :bold
    pdf.fill_color '000000'
    pdf.move_down 10

    # Audit Trail Table
    events_table = [['Timestamp', 'Action', 'Temperature', 'Location']]
    data[:events].each do |event|
      events_table << [
        event[:timestamp][0..19], 
        event[:action], 
        event[:temp], 
        event[:location]
      ]
    end

    pdf.table(events_table, width: 500, header: true) do
      row(0).font_style = :bold
      row(0).background_color = '#1e3c72'
      row(0).text_color = 'FFFFFF'
      cells.border_width = 1
      cells.border_color = 'CCCCCC'
    end

    # Compliance Footer
    pdf.move_down 30
    pdf.fill_color '#1e3c72'
    pdf.text_box 'ELECTRONIC SIGNATURE REQUIRED - 21 CFR §11.50(a)(1)(ii)', {
      at: [40, pdf.cursor], size: 12, style: :bold
    }
    pdf.fill_color '000000'
    pdf.move_down 10
    pdf.text "Generated by Thomas IT Pharma Transport SaaS | Phoenix, AZ", 
             size: 10, style: :bold
    pdf.text "Document validated against 21 CFR Part 11 requirements", size: 9

    pdf
  end
end
