source "https://rubygems.org"
ruby "3.2.2"

gem "rails", "~> 7.1.6"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# PHARMA SAAS - NO SOLID GEMS
gem "devise", "~> 4.9.4"
gem "devise-two-factor", "~> 5.1.0"
gem "stripe", "~> 10.15.0"
gem "prawn", "~> 2.5.0"
gem "rqrcode", "~> 3.2.0"
gem "tailwindcss-rails", "~> 2.7.9"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
